### ISSUE TITLE
Remove legacy bbPress exclude from MakePot

### ISSUE THREAD

**Issue by paulgibbs** [cedaro/node-wp-i18n#11]
Here https://github.com/cedaro/node-wp-i18n/blob/ac4810755b725bb421a521fb34fde0e56dcc065d/bin/php/makepot.php#L637 an exclude is added for the bundled version of bbPress v1 that comes bundled inside the BuddyPress plugin.

In the new year, our BuddyPress release is removing this bundled version of bbPress v1, so this exclude's no longer required. :)

**Comment by bradyvercher** [comment]
Thanks @paulgibbs! That file is straight from the core i18n tools and there's really no way to call that method from this package. If I ever update or replace the PHP library, I'll be sure to remove it then.
