### ISSUE TITLE
How to set custom POT headers

### ISSUE THREAD

**Issue by GaryJones** [cedaro/node-wp-i18n#18]
@bradyvercher For Genesis, we want to customize the POT Headers, such as `"Report-Msgid-Bugs-To: https://wordpress.org/support/theme/genesis\n"`, since that isn't correct.

We'd also like to include all of the POEdit headers, for those who want to use the `.pot` to create new catalogs via POEdit.

We also would like to use npm scripts, rather than the Grunt package that is currently being used.

Could you please explain how we'd go about setting these headers?

(Possibly having the npm script call a custom `.js` file that imported wpi18n and then set the desired `options.potHeaders` and passed `options` to `wpi18n.makepot`?)

Having this documented as a section in the Readme would be most helpful for those who want to do this sort of customisation.

**Comment by GaryJones** [comment]
Had to add `var wpi18n = require( 'node-wp-i18n' );` at the top of the `./bin/makepot.js` file, but otherwise it worked. Thanks!

**Comment by bradyvercher** [comment]
Doh! I knew I was going to forget to add that when replying. Glad to hear you got it working.
