### ISSUE TITLE
PHP 7.3 Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by NazarkinRoman** [cedaro/node-wp-i18n#22]
PHP 7.3 added a warning when `continue` word is used under `switch`. This leads to warnings in console when running any functions from `node-wp-i18n`.

```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in node_modules/node-wp-i18n/bin/php/pomo/plural-forms.php on line 210
```

**Comment by bradyvercher** [comment]
Thanks for the report @NazarkinRoman. This should be fixed in #21.
