### ISSUE TITLE
Warning: PO::export_entry(): Argument #1 ($entry) must be passed by reference

### ISSUE THREAD

**Issue by JJJ** [cedaro/node-wp-i18n#24]
PHP8 appears to trigger the following warning:

```
Warning: PO::export_entry(): Argument #1 ($entry) must be passed by reference, value given in /node_modules/.pnpm/node-wp-i18n@1.2.3/node_modules/node-wp-i18n/bin/php/pomo/po.php on line 52
```

**Comment by bradyvercher** [comment]
Hi @JJJ! I don't have a way to test this at the moment. Would you be willing to submit a PR or test?

I don't see why that argument needs to be passed by reference, so it might just be as simple as removing the `&`.

**Comment by bradyvercher** [comment]
I believe this should be good to go in 03b5c05
