### ISSUE TITLE
updateTimestamp broken (pot regenerated before parsing)

### ISSUE THREAD

**Issue by kraftner** [cedaro/node-wp-i18n#3]
You're checking the hash without the creation date which is good, but when you reset you [actually use the new date](https://github.com/cedaro/node-wp-i18n/blob/73966847fc0bc77fae7d13d9865ab8bffa80e4d3/lib/pot.js#L151) because [you've read "the old" value after already having regenerated](https://github.com/cedaro/node-wp-i18n/blob/73966847fc0bc77fae7d13d9865ab8bffa80e4d3/lib/makepot.js#L73).

**Comment by bradyvercher** [comment]
Thanks for the report @kraftner. Not sure what I was thinking there, but the latest commits should take care of this.
